# Generated by Django 5.1 on 2024-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_task_tasktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
