# Generated by Django 5.0.6 on 2024-08-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_task_tasktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
